select * from `TABLES`
WHERE TABLE_TYPE = 'BASE TABLE' AND `ENGINE` = 'InnoDB' AND TABLE_SCHEMA = 'homingse_dev'
-- WHERE TABLE_NAME LIKE 't_%'
ORDER BY TABLE_NAME DESC


select TABLE_NAME as '表名',TABLE_ROWS AS '表行数',CONCAT(ROUND(SUM(DATA_LENGTH) / (1024*1024*1024),12),'GB') AS '表空间大小'
from `TABLES`
WHERE TABLE_TYPE = 'BASE TABLE' AND `ENGINE` = 'InnoDB' AND TABLE_SCHEMA = 'homingse_dev'
-- WHERE TABLE_NAME LIKE 't_%'
GROUP BY TABLE_NAME
ORDER BY '每记录占用空间' DESC



SELECT * from `TABLES`
LIMIT 10


select TABLE_SCHEMA '库名',TABLE_NAME as '表名',TABLE_ROWS AS '表行数',CONCAT(ROUND(DATA_LENGTH / (1024*1024),2)) AS '表空间大小(M)',
        (CONCAT(ROUND(DATA_LENGTH / (1024*1024),2)) / TABLE_ROWS) as '每记录平均占用空间(M)'
from `TABLES`
WHERE TABLE_TYPE = 'BASE TABLE' AND `ENGINE` = 'InnoDB' 
-- WHERE TABLE_NAME LIKE 't_%' --AND TABLE_SCHEMA = 'homingse_dev'
GROUP BY TABLE_SCHEMA,TABLE_NAME
ORDER BY (DATA_LENGTH / TABLE_ROWS) DESC


select sum(TABLE_ROWS),CONCAT(ROUND(SUM(DATA_LENGTH) / (1024*1024*1024),2),'GB') AS '表空间大小' from `TABLES`
WHERE TABLE_TYPE = 'BASE TABLE' AND `ENGINE` = 'InnoDB' AND TABLE_SCHEMA = 'homingse_dev'
-- WHERE TABLE_NAME LIKE 't_%'
ORDER BY TABLE_NAME DESC




select TABLE_NAME as '表名',TABLE_ROWS AS '表行数',DATA_LENGTH AS '表空间大小',
        (DATA_LENGTH / TABLE_ROWS) as '每记录平均占用空间'
from `TABLES`
WHERE TABLE_TYPE = 'BASE TABLE' AND `ENGINE` = 'InnoDB' AND TABLE_SCHEMA = 'homingse_dev'
-- WHERE TABLE_NAME LIKE 't_%'
GROUP BY TABLE_NAME
ORDER BY (DATA_LENGTH / TABLE_ROWS) DESC
